services:
  openvas:
    image: immauss/openvas:latest
    container_name: openvas
    hostname: openvas
    restart: unless-stopped
    ports:
      - "${OPENVAS_HTTPS_PORT:-8080}:9392"
    environment:
      USERNAME: ${OPENVAS_USERNAME}
      PASSWORD: ${OPENVAS_PASSWORD}
      HTTPS: true
      RELAYHOST: ""
      SMTPPORT: 25
      REDISDBS: 512
    volumes:
      - openvas_data:/data

volumes:
  openvas_data:
