services:
  openvas:
    image: immauss/openvas:latest
    container_name: openvas
    hostname: openvas
    restart: unless-stopped
    ports:
      - "8080:9392"
    environment:
      USERNAME: admin
      PASSWORD: admin
      HTTPS: true
      RELAYHOST: ""
      SMTPPORT: 25
      REDISDBS: 512
    volumes:
      - openvas_data:/data

volumes:
  openvas_data:
